### ISSUE TITLE
Fix dependencies conflicts (TensorFlow)

### ISSUE THREAD

**Issue by Axelvel** [galyfray/CVRP#11]
Create 2 requirements.txt files: one for macOS and one for Windows/Linux.
Modify the Makefile to use the right file depending on the platform.

**Comment by galyfray** [comment]
Please test the latest commit done to the DRL branch and close this issue if it correctly installs TensorFlow on Mac.

**Comment by Axelvel** [comment]
Thanks, TensorFlow works now 👍
