### ISSUE TITLE
Fix missing dependencies #10 

### ISSUE THREAD

**Issue by galyfray** [galyfray/CVRP#19]
Pydocstyle is not part of the required dependencies any more in this PR. 
I didn't go thought each and every of the dependencies, but it might not be the only one.

**Comment by Axelvel** [comment]
Added a few dependencies to requirements_mac.txt and requirements.txt, mainly:
- pydocstyle
- pytest
- bandit
- flake8
- pylint
- coverage

**Comment by Axelvel** [comment]
@galyfray There seems to be some dependencies conflicts for Linux/Windows that I don't have on macOS, could you solve them and push the fix?

**Comment by galyfray** [comment]
Dependencies are fixed. @Axelvel can you produce a small test suite to check that code working with your tensorflow version will work and as expected on linux/windows ?
